name = "LeanArchitect-example"
defaultTargets = ["Example"]

[[require]]
name = "LeanArchitect"
scope = "hanwenzhu"
rev = "main"

[[require]]
name = "checkdecls"
scope = "PatrickMassot"

[[lean_lib]]
name = "Example"
